// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UFArt.Models;

namespace UFArt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181022120103_ArtPieceModified")]
    partial class ArtPieceModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UFArt.Models.Gallery.ArtPiece", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Dimensions");

                    b.Property<bool>("ForSale");

                    b.Property<string>("ImageUri");

                    b.Property<string>("Name");

                    b.Property<string>("Technique")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ArtPieces");
                });

            modelBuilder.Entity("UFArt.Models.Gallery.TechniqueDict", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeName");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("UFArt.Models.Newsfeed.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Header");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Text");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.ToTable("News");
                });
#pragma warning restore 612, 618
        }
    }
}
